apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: podinfo  
spec:  
  generators:  
  - git:  
      repoURL: https://github.com/jerryyanmj/harness-gitops-workshop.git  
      revision: HEAD  
      directories:
      - path: configs/git-generator-files-discovery/cluster-config/**/config.json
  template:  
    metadata:  
      name: '{{cluster.namespace}}-podinfo'  
    spec:  
      project: default  
      source:  
        repoURL: https://github.com/jerryyanmj/harness-gitops-workshop.git  
        targetRevision: HEAD  
        path: "configs/git-generator-files-discovery/apps/podinfo"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: '{{cluster.namespace}}'  
      syncPolicy:  
        syncOptions:
        - CreateNamespace=true
